"""
Configuration constants and paths for experiment plotting.

This module serves as the single source of truth for all magic numbers,
file paths, and plot settings used throughout the plotting utilities.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal


# =============================================================================
# Algorithm Parameters
# =============================================================================

# Default RRF (Reciprocal Rank Fusion) constant for graded relevance
# Used in NDCG computation: relevance = 1 / (k_rrf + rank)
DEFAULT_RRF_K: float = 60.0

# Pivot count and expansion factor values for P×X experiments
PIVOT_VALUES: list[int] = [1, 2, 4, 8, 16]

# Window sizes for sort experiments (K=10 from base experiments, rest from sort experiments)
SORT_WINDOW_VALUES: list[int] = [10, 20, 50, 100, 250, 500, 750, 1000]

# Window sizes for window sweep experiments
WINDOW_SWEEP_VALUES: list[int] = [4, 8, 16, 32, 48, 64, 128]

# K values for top-K experiments
K_VALUES: list[int] = [10, 20, 50, 100]

# Tournament filter document counts mapped to L values
TFILTER_DOC_NUMS: dict[int, int] = {
    1: 260,
    5: 1295,
    10: 2591,
    15: 3887,
}

# Sort window values for wsort experiments (W values, L=20 fixed)
WSORT_VALUES: list[int] = [2, 4, 8, 9, 10, 16, 20]

# Default number of queries per experiment
DEFAULT_NUM_QUERIES: int = 25

# Confidence interval type for comparison plots: "std" (±1 std) or "iqr" (25th-75th percentile)
CI_TYPE: str = "std"


# =============================================================================
# File Paths
# =============================================================================

# Base directories for organized data structure
DATA_RAW_DIR: Path = Path("./data/raw/")
DATA_DERIVED_DIR: Path = Path("./data/derived/")
PLOTS_DIR: Path = Path("./plots/")

# Ground truth rankings path (derived data)
GROUND_TRUTH_PATH: Path = DATA_DERIVED_DIR / "llm-topk-gt/data/phase7_combined_rankings/scifact/"

# Raw data directory paths
DATA_PATHS: dict[str, Path] = {
    "early_stopping": DATA_RAW_DIR / "5000e/",
    "no_early_stopping": DATA_RAW_DIR / "5000/",
    "window_sweep": DATA_RAW_DIR / "5000w/",
    "tfilter": DATA_RAW_DIR / "tfilter/",
    "sort": DATA_RAW_DIR / "sort/",
    "sort_hgt_metrics": DATA_RAW_DIR / "sort/hgt_metrics/",
    "k5000": DATA_RAW_DIR / "k5000/",
    "comparison": DATA_RAW_DIR / "comparison_1_data/",
    "no_embedding_pivot": DATA_RAW_DIR / "no-em-p/",
    "wsort": DATA_RAW_DIR / "wsortdata/",
    "tourk5000": DATA_RAW_DIR / "tourk5000/",
}

# HGT data paths for different L values (derived data)
HGT_DATA_PATHS: dict[str, Path] = {
    "pairwise": DATA_DERIVED_DIR / "hgt_data/pairwise_data/",
    "base": DATA_DERIVED_DIR / "hgt_data/16_2_data/",
    "l1": DATA_DERIVED_DIR / "hgt_data/l1data/",
    "l2": DATA_DERIVED_DIR / "hgt_data/l2data/",
    "l5": DATA_DERIVED_DIR / "hgt_data/l5data/",
    "l10": DATA_DERIVED_DIR / "hgt_data/l10data/",
    "l15": DATA_DERIVED_DIR / "hgt_data/l15data/",
    "w128": DATA_DERIVED_DIR / "hgt_data/w128data/",
}

# HGT pair data paths - pairwise quicksort replaces LMPQsort for final sorting (raw data)
HGT_PAIR_PATHS: dict[str, Path] = {
    "l1": DATA_RAW_DIR / "hgt_pair/l1/",
    "l2": DATA_RAW_DIR / "hgt_pair/l2/",
    "l5": DATA_RAW_DIR / "hgt_pair/l5/",
    "l10": DATA_RAW_DIR / "hgt_pair/l10/",
    "l15": DATA_RAW_DIR / "hgt_pair/l15/",
    "l20": DATA_RAW_DIR / "wsortdata/",  # L=20 W=2 pairwise data
    "w128": DATA_RAW_DIR / "hgt_pair/w128/",
}

# LOTUS baseline paths (raw data)
LOTUS_PATHS: dict[str, Path] = {
    "zephyr_7b": DATA_RAW_DIR / "lotusk/combined_z7b/",
    "qwen3_8b": DATA_RAW_DIR / "lotusk/qwen_data/",
}

# Pointwise baseline paths (raw data)
POINTWISE_PATHS: dict[str, Path] = {
    "zephyr": DATA_RAW_DIR / "bier_pointwise/zephyr/",
    "qwen3_8b": DATA_RAW_DIR / "bier_pointwise/qwen/",
}

# DLLM (different LLM backends for LMPQSelect/Sort) paths (raw data)
DLLM_PATHS: dict[str, Path] = {
    "zephyr7b": DATA_RAW_DIR / "dllmdata/zephyr/",
    "qwen3_8b": DATA_RAW_DIR / "dllmdata/qwen/",
}

# Computed LLM ground truth metrics (derived data, generated by compute_baseline_metrics.py)
LLM_GT_METRICS_PATH: Path = DATA_DERIVED_DIR / "llm_gt_metrics/"

# Computed LLM ground truth metrics for HGT pair data (pairwise quicksort final sort)
HGT_PAIR_LLM_METRICS_PATH: Path = DATA_DERIVED_DIR / "hgt_pair_llm_metrics/"

# Tour directory paths (raw data, using bug-fixed versions where available)
TOUR_PATHS: dict[int, Path] = {
    1: DATA_RAW_DIR / "Tour_1/",
    2: DATA_RAW_DIR / "Tour_2/",
    5: DATA_RAW_DIR / "tour5-b/",
    10: DATA_RAW_DIR / "Tour_10-b/",
    15: DATA_RAW_DIR / "tour_15-b/",
}

# LTFilter + Tournament Top-K data paths (tfilter for selection, tournament sort for final ordering)
LTFILTER_LTTOPK_PATH: Path = DATA_RAW_DIR / "tfilter-tsort-data/"


# =============================================================================
# File Name Templates
# =============================================================================

def result_filename(p: int, x: int, queries: int = DEFAULT_NUM_QUERIES) -> str:
    """Generate result filename for given parameters."""
    return f"bier_result_unsorted_{p}_{x}_{queries}.csv"


def metrics_filename(p: int, x: int, queries: int = DEFAULT_NUM_QUERIES) -> str:
    """Generate metrics filename for given parameters."""
    return f"bier_metrics_{p}_{x}_{queries}.csv"


def sorted_metrics_filename(
    p: int, x: int, l: int, w: int, k: int, queries: int = DEFAULT_NUM_QUERIES
) -> str:
    """Generate sorted metrics filename for given parameters."""
    return f"bier_metrics_sorted_{p}_{x}_{l}_{w}_{k}_{queries}.csv"


def tfilter_filename(doc_num: int, queries: int = DEFAULT_NUM_QUERIES) -> str:
    """Generate tournament filter result filename."""
    return f"bier_tfilter_result_{doc_num}_{queries}.csv"


def sort_result_filename(window: int, queries: int = DEFAULT_NUM_QUERIES) -> str:
    """Generate sort result filename."""
    return f"bier_sort_result_{window}_{queries}.csv"


def window_sweep_filename(window: int, queries: int = DEFAULT_NUM_QUERIES) -> str:
    """Generate window sweep result filename."""
    return f"bier_result_unsorted_E_{window}_{queries}_A.csv"


# =============================================================================
# Plot Configuration
# =============================================================================

@dataclass
class HeatmapConfig:
    """Configuration for heatmap plots."""
    cmap: str
    vmin: float
    vmax: float
    center: float = 0
    fmt: str = ".2f"
    figsize: tuple[int, int] = (10, 8)


# Heatmap configurations by metric type
HEATMAP_CONFIGS: dict[str, HeatmapConfig] = {
    "time": HeatmapConfig(cmap="viridis", vmin=300, vmax=6000),
    "recall": HeatmapConfig(cmap="plasma", vmin=0, vmax=1),
}


@dataclass
class MethodConfig:
    """Configuration for a single method in comparison plots."""
    label: str
    color: str
    path: Path | None = None
    hgt_path: Path | None = None


# =============================================================================
# Canonical Method Colors and Ordering for Main Comparison Plots
# =============================================================================
# Using Paul Tol's vibrant color scheme for accessibility:
# #0077BB, #33BBEE, #009988, #EE7733, #CC3311, #EE3377
# Variants of the same method family share the same color;
# LLM backend is distinguished by marker shape (see METHOD_MARKERS).

METHOD_COLORS: dict[str, str] = {
    "tournament": "#0077BB",           # Blue
    # LMPQSelect/Sort variants (single family color)
    "lmpqselect": "#33BBEE",           # Cyan
    "lmpqselect_zephyr7b": "#33BBEE",  # Cyan (same family)
    "lmpqselect_qwen3_8b": "#33BBEE",  # Cyan (same family)
    "pairwise": "#009988",             # Teal
    # LOTUS variants (single family color)
    "lotus_qwen": "#EE7733",           # Orange
    "lotus_zephyr": "#EE7733",         # Orange (same family)
    # Pointwise variants (single family color)
    "pointwise_qwen": "#CC3311",       # Red
    "pointwise_zephyr": "#CC3311",     # Red (same family)
}

# Marker shapes per method: circle=RankZephyr, square=Zephyr, star=Qwen
METHOD_MARKERS: dict[str, str] = {
    "tournament": "o",
    "lmpqselect": "o",
    "lmpqselect_zephyr7b": "s",
    "lmpqselect_qwen3_8b": "*",
    "pairwise": "o",
    "lotus_qwen": "*",
    "lotus_zephyr": "s",
    "pointwise_qwen": "*",
    "pointwise_zephyr": "s",
}

# Method family colors for legend (ordered)
METHOD_FAMILY_COLORS: dict[str, str] = {
    "Tournament": "#0077BB",
    "LMPQ": "#33BBEE",
    "LTFilter+LMPQ\n(S=1,2,5,10,15)": "#994F88",
    "Pairwise": "#009988",
    "LOTUS": "#EE7733",
    "Pointwise": "#CC3311",
}

# LLM backend markers for legend (ordered)
LLM_BACKEND_MARKERS: dict[str, str] = {
    "RankZephyr": "o",
    "Zephyr-7B": "s",
    "QWEN3-8B": "*",
}

# LTFilter+LMPQSelect/Sort gradient (Paul Tol discrete rainbow subset - purples)
# Ordered from S=1 (lightest) to S=15 (darkest)
# Using shades of purple to show S parameter variation
LTFILTER_COLORS: dict[int, str] = {
    1: "#BA8DB4",   # Lightest purple
    2: "#AA6F9E",   # Light-medium purple
    5: "#994F88",   # Medium purple
    10: "#882E72",  # Dark purple
    15: "#6B1D5C",  # Darkest purple
}

# LTFilter+LTTopK gradient (shades of green to distinguish from LMPQ)
# Ordered from S=1 (lightest) to S=15 (darkest)
LTFILTER_LTTOPK_COLORS: dict[int, str] = {
    1: "#88CCAA",   # Lightest green
    5: "#44AA88",   # Light-medium green
    10: "#117755",  # Medium green
    15: "#004433",  # Darkest green
}

# Canonical method labels
METHOD_LABELS: dict[str, str] = {
    "tournament": "LTTopK (RankZephyr)",
    "lmpqselect": "LMPQ (RankZephyr)",
    "lmpqselect_zephyr7b": "LMPQ (Zephyr7b)",
    "lmpqselect_qwen3_8b": "LMPQ (Qwen3-8b)",
    "ltfilter": "LTFilter+LMPQ (RankZephyr)",
    "ltfilter_lttopk": "LTFilter+LTTopK (RankZephyr)",
    "pairwise": "Pairwise (RankZephyr)",
    "lotus_qwen": "LOTUS (QWEN3-8B)",
    "lotus_zephyr": "LOTUS (Zephyr-7B)",
    "pointwise_qwen": "Pointwise (QWEN3-8B)",
    "pointwise_zephyr": "Pointwise (Zephyr-7B)",
}

# Canonical ordering for legend and plotting (index determines order)
# Lower index = plotted/listed first
METHOD_ORDER: list[str] = [
    "tournament",
    "lmpqselect",
    "ltfilter",           # Line group with S variants
    "ltfilter_lttopk",    # Line group with S variants (LTFilter + Tournament Top-K)
    "pairwise",
    "lmpqselect_zephyr7b",
    "lmpqselect_qwen3_8b",
    "lotus_qwen",
    "lotus_zephyr",
    "pointwise_qwen",
    "pointwise_zephyr",
]

# Marker sizes (diameter in points^2, so 30% smaller diameter = 0.7^2 ≈ 0.49 of area)
MARKER_SIZE_NORMAL: float = 40    # Was 80, now ~49% area (70% diameter)
MARKER_SIZE_SMALL: float = 20     # Was 40, now ~49% area (70% diameter)

# Legacy compatibility
COMPARISON_METHODS: list[MethodConfig] = [
    MethodConfig("pairwise", METHOD_COLORS["pairwise"]),
    MethodConfig("L=20", METHOD_COLORS["lmpqselect"]),
    MethodConfig("Tournament Sort", METHOD_COLORS["tournament"]),
]

# Simplified color palette for plots
DEFAULT_COLORS: list[str] = list(METHOD_COLORS.values())


# =============================================================================
# Plot Labels and Titles
# =============================================================================

@dataclass
class PlotLabels:
    """Standard labels for plot axes and titles."""
    latency: str = "Latency (s)"
    recall_at_k: str = "Recall@{k}"
    ndcg_at_k: str = "NDCG@{k}"
    pivot_p: str = "P"
    expansion_x: str = "X"
    window_w: str = "W"
    list_length_l: str = "L"
    top_k: str = "K"


LABELS = PlotLabels()


# =============================================================================
# Metric Column Names
# =============================================================================

METRIC_COLUMNS: dict[str, str] = {
    "ndcg": "NDCG@10",
    "map": "MAP@10",
    "recall": "Recall@10",
    "precision": "P@10",
    "time": "time",
}


# =============================================================================
# Fallback Paths for Missing Metrics
# =============================================================================

# Fallback subdirectories for metrics lookup (used in calc_stats_for_5000_hgt)
METRICS_FALLBACK_SUBDIRS: list[str] = [
    "4_1_combined",
    "16_1_combined",
    "16_2_combined",
]
